language: python
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    python: 2.7
  - os: linux
    dist: trusty
    sudo: required
    python: 3.4
  - os: osx
    osx_image: xcode8.1
    language: generic
    env: PYTHONPATH=/Library/Python/2.7/site-packages/
install:
  - ./config/travis/install.sh
script:
  - if test ${TRAVIS_OS_NAME} = "osx"; then PYTHONPATH=/Library/Python/2.7/site-packages/ /usr/bin/python ./run_tests.py; elif test ${TRAVIS_OS_NAME} = "linux"; then if test ${TRAVIS_PYTHON_VERSION} = "2.7"; then coverage run --source=l2tdevtools --omit="*_test*,*__init__*,*test_lib*" ./run_tests.py; else ./run_tests.py; fi; fi
after_success:
  - if test ${TRAVIS_OS_NAME} = "linux" && test ${TRAVIS_PYTHON_VERSION} = "2.7"; then coveralls --verbose; fi
