environment:
  matrix:
  - TARGET: unittests
    MACHINE_TYPE: "x86"
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7"
  - TARGET: unittests
    MACHINE_TYPE: "amd64"
    PYTHON: "C:\\Python27-x64"
    PYTHON_VERSION: "2.7"
  - TARGET: unittests
    MACHINE_TYPE: "x86"
    PYTHON: "C:\\Python37"
    PYTHON_VERSION: "3.7"
  - TARGET: unittests
    MACHINE_TYPE: "amd64"
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7"

install:
- cmd: '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x86 /release'
- cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip"
- cmd: "%PYTHON%\\python.exe -m pip install pywin32 WMI"
- cmd: "%PYTHON%\\python.exe %PYTHON%\\Scripts\\pywin32_postinstall.py -install"

build: off

test_script:
- cmd: if [%TARGET%]==[unittests] (
    "%PYTHON%\\python.exe" run_tests.py )
